/*
 * BookUpdate.java
 *
 * Created on __DATE__, __TIME__
 */

package maylor.system.ui;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.JOptionPane;

import maylor.system.factory.DAOFactory;
import maylor.system.util.DateUtil;
import maylor.system.model.Book;

/**
 * 
 * @author __USER__
 */
public class BookUpdate extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6545894124600040519L;

	/** Creates new form BookUpdate */
	public BookUpdate() {
		super("Library Book Update");
		Image ime = Toolkit.getDefaultToolkit().getImage(
				("/images/ico.png"));
		setIconImage(ime);
		initComponents();
		this.setResizable(false);
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel7 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel1.setText("\u56fe\u4e66\u4fee\u6539");

		jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel3.setText("\u539f\u56fe\u4e66");

		jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel4.setText("\u65b0\u56fe\u4e66");

		jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel5.setText("\u56fe\u4e66\u7f16\u53f7\uff1a");

		jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel6.setText("\u56fe\u4e66\u7f16\u53f7\uff1a");

		jButton1.setBackground(new java.awt.Color(223, 216, 216));
		jButton1.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel7.setText(" \u540d      \u79f0\uff1a");

		jTextField3.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel8.setText(" \u4f5c      \u8005\uff1a");

		jTextField4.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel9.setText("\u7c7b       \u522b\uff1a");

		jLabel10.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel10.setText("\u4ef7       \u683c\uff1a");

		jTextField6.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel11.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel11.setText("\u51fa\u7248\u65f6\u95f4\uff1a");

		jTextField7.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel12.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel12.setText("\u4ecb      \u7ecd\uff1a");

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel14.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel14.setText("bookid");

		jLabel15.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel15.setText("\u540d        \u79f0\uff1a");

		jTextField8.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel16.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel16.setText("\u4f5c        \u8005\uff1a");

		jTextField9.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel17.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel17.setText("\u7c7b        \u522b\uff1a");

		jLabel18.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel18.setText("\u4ef7        \u683c\uff1a");

		jTextField11.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel19.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel19.setText("\u51fa\u7248\u65f6\u95f4\uff1a");

		jTextField12.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jLabel20.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jLabel20.setText("\u4ecb        \u7ecd\uff1a");

		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jButton2.setBackground(new java.awt.Color(223, 216, 216));
		jButton2.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton2.setText("save");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(223, 216, 216));
		jButton3.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton3.setText("close");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField1.setFont(new java.awt.Font("微软雅黑", 0, 14));

		jComboBox1.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"文化、科学、教育、体育", "政治、法律", "农业科学", "生物科学", "经济", "文学", "哲学",
				"计算机", "语言、文字", "天文学、地理科学", "医学、卫生", "综合性图书", "其他" }));

		jComboBox2.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"文化、科学、教育、体育", "政治、法律", "农业科学", "生物科学", "经济", "文学", "哲学",
				"计算机", "语言、文字", "天文学、地理科学", "医学、卫生", "综合性图书", "其他" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(130, 130, 130)
								.addComponent(jLabel3).addGap(347, 347, 347)
								.addComponent(jLabel4).addGap(161, 161, 161))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addComponent(jLabel7)
												.addComponent(jLabel8)
												.addComponent(jLabel9)
												.addComponent(jLabel10)
												.addComponent(jLabel11)
												.addComponent(jLabel12))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jLabel14,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														262, Short.MAX_VALUE)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		jTextField7,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jTextField6,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jTextField4,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jTextField3,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		228,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2)
																.addComponent(
																		jComboBox1,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		0,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel15)
																				.addComponent(
																						jLabel16)
																				.addComponent(
																						jLabel17)
																				.addComponent(
																						jLabel18)
																				.addComponent(
																						jLabel19)
																				.addComponent(
																						jLabel20))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jComboBox2,
																						0,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane2)
																				.addComponent(
																						jTextField12)
																				.addComponent(
																						jTextField11)
																				.addComponent(
																						jTextField9)
																				.addComponent(
																						jTextField8)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(35, 35,
																		35)
																.addComponent(
																		jButton3)))
								.addGap(19, 19, 19))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(165, 165, 165)
								.addComponent(jLabel5)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										224,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1)
								.addContainerGap(190, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup().addGap(302, 302, 302)
								.addComponent(jLabel1)
								.addContainerGap(348, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(64, 64, 64)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										569,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(89, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jLabel5,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jButton1)
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		30,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										10,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(jLabel4))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						jLabel14,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						27,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jTextField4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel9)
																				.addComponent(
																						jComboBox1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel10)
																				.addComponent(
																						jTextField6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel11)
																				.addComponent(
																						jTextField7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						100,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel12)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(45, 45,
																		45)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel15)
																				.addComponent(
																						jTextField8,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel16)
																				.addComponent(
																						jTextField9,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel17)
																				.addComponent(
																						jComboBox2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel18)
																				.addComponent(
																						jTextField11,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel19)
																				.addComponent(
																						jTextField12,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel20))))
								.addGap(78, 78, 78)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton3))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// 接受修改后的图书信息:
		String id = jTextField1.getText();
		String name = jTextField8.getText();
		String author = jTextField9.getText();
		String classify = (String) jComboBox2.getSelectedItem();
		String price = jTextField11.getText();
		String publishdata = jTextField12.getText();
		String news = jTextArea2.getText();
		Book book = new Book();
		book.setId(id);
		book.setName(name);
		book.setAuthor(author);
		book.setClassify(classify);
		book.setPrice(Double.parseDouble(price));
		book.setNews(news);
		book.setPublishdata(DateUtil.getStringToDate(publishdata));
		boolean flag = false;
		if(book!=null){
			try {
				flag = DAOFactory.getIBookDAOInstance().doUpdate(book);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if (flag) {
				JOptionPane.showMessageDialog(null, "修改成功！", "消息", 1);
			}
			else{
				JOptionPane.showMessageDialog(null, "操作错误！", "消息", 1);
			}
		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// 查询图书
		String searchid = jTextField1.getText();
		if (searchid != null && !searchid.equals("")) {
			try {
				Book book = DAOFactory.getIBookDAOInstance().findById(
						searchid);
				if (book != null) {
					jLabel14.setText(String.valueOf(book.getId()));
					jTextField3.setText(book.getName());
					jTextField4.setText(book.getAuthor());
					jComboBox1.setSelectedItem(book.getClassify());
					jTextField6.setText(String.valueOf(book.getPrice()));
					jTextField7.setText(String.valueOf(book.getPublishdata()));
					jTextArea1.setText(book.getNews());
				} else {
					JOptionPane.showMessageDialog(null, "没有你要查询的书籍！", "消息", 1);
				}

			} catch (NumberFormatException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			JOptionPane.showMessageDialog(null, "没有你要查询的书籍！", "消息", 1);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void start() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BookUpdate().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}