/*
 * BookUpdate.java
 *
 * Created on __DATE__, __TIME__
 */

package maylor.system.ui;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.JOptionPane;

import maylor.system.factory.DAOFactory;
import maylor.system.model.Reader;

/**
 * 
 * @author __USER__
 */
public class ReaderUpdate extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5185636646627693500L;

	/** Creates new form BookUpdate */
	public ReaderUpdate() {
		super("Library Reader Update");
		Image ime = Toolkit.getDefaultToolkit().getImage(
				("/images/ico.png"));
		setIconImage(ime);
		initComponents();
		this.setResizable(false);
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel7 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jComboBox4 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel1.setText("\u8bfb\u8005\u4fee\u6539");

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel3.setText("\u539f\u4fe1\u606f");

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel4.setText("\u65b0\u4fe1\u606f");

		jLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel5.setText("\u8bfb\u8005\u7f16\u53f7\uff1a");

		jLabel6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel6.setText("\u8bfb\u8005\u7f16\u53f7\uff1a");

		jButton1.setBackground(new java.awt.Color(223, 216, 216));
		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel7.setText("\u8bfb\u8005\u59d3\u540d\uff1a");

		jTextField3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jLabel9.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel9.setText("\u7c7b       \u522b\uff1a");

		jLabel14.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel14.setText("Login_id");

		jTextField8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jButton2.setBackground(new java.awt.Color(223, 216, 216));
		jButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton2.setText("save");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(223, 216, 216));
		jButton3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jButton3.setText("close");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jComboBox1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Ñ§Éú", "½ÌÊ¦", "ÆäËû" }));

		jComboBox2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Ñ§Éú", "½ÌÊ¦", "ÆäËû" }));

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel2.setText("\u501f\u4e66\u671f\u9650\uff1a");

		jTextField2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jTextField4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));

		jLabel8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jLabel8.setText("\u6027       \u522b\uff1a");

		jComboBox3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"ÄÐ", "Å®" }));

		jComboBox4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 14));
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"ÄÐ", "Å®" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						jLabel9))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										jTextField3,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										122,
																																										javax.swing.GroupLayout.PREFERRED_SIZE))
																																				.addComponent(
																																						jComboBox1,
																																						0,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jComboBox2,
																																						0,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						jTextField8,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						122,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addComponent(
																														jLabel14,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														139,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										9,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(24,
																										24,
																										24)
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										105,
																										Short.MAX_VALUE)
																								.addComponent(
																										jLabel4)
																								.addGap(52,
																										52,
																										52))))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel5)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		199,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addComponent(jSeparator1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 366,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup().addGap(111, 111, 111)
								.addComponent(jButton2).addGap(62, 62, 62)
								.addComponent(jButton3)
								.addContainerGap(65, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup().addGap(147, 147, 147)
								.addComponent(jLabel1)
								.addContainerGap(147, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										124, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jTextField4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										122,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(21, 21, 21))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel8)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jComboBox3, 0, 124,
										Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										122,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(21, 21, 21)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel5,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(jButton1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(14, 14, 14)
								.addComponent(jSeparator1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										15,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(jLabel4))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														jLabel14,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														27,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel7)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField8,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(
														jComboBox3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jComboBox4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel9)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jComboBox2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(36, 36, 36)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton3))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// ½ÓÊÜÐÞ¸ÄºóµÄÓÃ»§ÐÅÏ¢:
		String id = jLabel14.getText();
		String name = jTextField8.getText();
		String sex = (String) jComboBox4.getSelectedItem();
		String type = (String) jComboBox2.getSelectedItem();
		int days_num = Integer.parseInt(jTextField4.getText());

		if (id != null && !id.equals("")) {
			
			Reader reader = new Reader();
			reader.setId(id);
			reader.setName(name);
			reader.setSex(sex);
			reader.setType(type);
			reader.setDays_num(days_num);
			boolean flag = false;
			if (reader != null) {
				try {
					flag = DAOFactory.getIReaderDAOInstance().doUpdate(reader);
					if (flag) {
						JOptionPane.showMessageDialog(null, "ÐÞ¸Ä³É¹¦£¡", "ÏûÏ¢", 1);
					}
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}else {
			JOptionPane.showMessageDialog(null, "²»´æÔÚ¸Ã¶ÁÕß£¡", "ÏûÏ¢", 1);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// ²éÑ¯ÓÃ»§
		String searchid = jTextField1.getText();
		if (searchid != null && !searchid.equals("")) {
			try {
				Reader reader = DAOFactory.getIReaderDAOInstance().findById(
						searchid);
				if (reader != null) {
					jLabel14.setText(String.valueOf(reader.getId()));
					jTextField3.setText(reader.getName());
					jComboBox3.setSelectedItem(reader.getSex());
					jComboBox1.setSelectedItem(reader.getType());
					jTextField2.setText(String.valueOf(reader.getDays_num()));

					jTextField2.setEditable(false);
					jTextField3.setEditable(false);
					jComboBox3.setEditable(false);
					jComboBox1.setEditable(false);
				} else {
					JOptionPane.showMessageDialog(null, "²»´æÔÚ¸Ã¶ÁÕß£¡", "ÏûÏ¢", 1);
				}

			} catch (NumberFormatException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			JOptionPane.showMessageDialog(null, "²»´æÔÚ¸Ã¶ÁÕß£¡", "ÏûÏ¢", 1);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void start() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ReaderUpdate().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration//GEN-END:variables

}